### ISSUE TITLE
Please add a readme

### ISSUE THREAD

**Issue by DanielBallaSZTE** [crippin/twitch-webos#1]

**Comment by danilokleber** [comment]
Hello @crippin, thanks for putting this app together and sharing it with us.

I know you added a README file, but I still couldn't install it on my TV. There seems to be an error with some Firebase credentials when I try running `yarn start`. Do you know what I can do to get rid of those errors?

```
ERROR in ./node_modules/@firebase/polyfill/dist/index.esm.js
Module not found: Error: Can't resolve 'core-js/features/symbol' in '/Users/bytes/twitch-webos/node_modules/@firebase/polyfill/dist'
 @ ./node_modules/@firebase/polyfill/dist/index.esm.js 8:0-33
 @ ./node_modules/firebase/app/dist/index.cjs.js
 @ ./src/OAuth.js
 @ ./src/App.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 babel-polyfill ./src/App.js
```

**Comment by copymark** [comment]
well you have to download your dependencies first:

use: `yarn install`

**Comment by danilokleber** [comment]
Thanks for the quick reply! I had done it and now running again it gives me:

```
yarn install v1.12.3
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.54s.
```

Is it something with my yarn version?

**Comment by danilokleber** [comment]
I don't think it is a problem with the yarn version but with the polyfill module on the firebase one.

Maybe this issue can help debugging. Sorry I'm not initiated on JS.

**Comment by copymark** [comment]
in webpack.config.babel.js:

Replace

`modules: [sourcePath, path.resolve(__dirname, 'node_modules')]`

with 

`modules: [sourcePath, path.resolve(__dirname, 'node_modules'), 'node_modules'],`

Seems to be a bug. Maybe the actual project owner has some special configuration on his pc....

**Comment by crippin** [comment]
@danilokleber @copymark I will check it out in the weekends, and also upstream my latest local changes to the master branch. I appreciate your interest in this project. :)
